# -*- coding: utf-8 -*-
"""OpenCV-人臉偵測&截取-許庭瑋-0809.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10jWN0Ds10e88qU5AYIsq4sooLqm3cElh
"""

!pip install opencv-python

import cv2
import numpy
from google.colab.patches import cv2_imshow 
from google.colab import files

# 上傳檔案至colab
uploaded = files.upload()

# 讀取影像檔案 cv2.imread('檔案存放路徑',附加設定)
img = cv2.imread('/content/5566.jpg')

# 顯示影像 cv2_imshow('視窗名稱','變數名稱',附加設定)
cv2_imshow(img)

# opencv 內建分類模型存放路徑
casc_path = cv2.data.haarcascades+"haarcascade_frontalface_default.xml"

# 建立偵測物件 cv2.CascadeClassifier(模型存放路徑)
face_casc = cv2.CascadeClassifier(casc_path)

# 使用物件 detectMultiScale 偵測臉部
# 名稱.detectMultiScale('圖片物件',搜索框大小,最小鄰居認定標準,圖檔最小尺寸,邊緣處理方式)
faces = face_casc.detectMultiScale(img,
                    scaleFactor=1.1,
                    minNeighbors=5,
                    minSize=(30,30),
                    flags = cv2.CASCADE_SCALE_IMAGE)

# 顯示偵測到幾張人臉
print(len(faces))
# 人臉座標
print(faces[0])

print(faces[1])

#用cv2.rectangle 框出人臉 
cv2.rectangle(img,(faces[0][0],faces[0][1]),
       (faces[0][0]+faces[0][2],faces[0][1]+faces[0][3]),
       (0,0,255),2)

cv2_imshow(img)

# 找出所有人臉並框出
for (x,y,w,h) in faces:
  cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)

cv2_imshow(img)

img.shape[0]

img.shape[1]

#在圖片上註記想要的文字
temp = "OpenCV find "+str(len(faces))+" face!"

# 原始檔案大小
img_h = img.shape[0]
img_w = img.shape[1]

cv2.putText(img,temp,(25,img_h-15),cv2.FONT_HERSHEY_PLAIN,
  1, (0, 0, 255), 1, cv2.LINE_AA)
cv2.putText(img,author,(250,img_h-15),cv2.FONT_HERSHEY_PLAIN,
  1, (255, 0, 0), 1, cv2.LINE_AA)

cv2_imshow(img)

# 座標
x = faces[1][0]
y = faces[1][1]
w = faces[1][2]
h = faces[1][3]

# 截取人臉
face1 = img[y:y+h,x:x+w]
cv2_imshow(face1)

# 印出所有人臉
for (x,y,w,h) in faces:
  face_all = img[y:y+h,x:x+w]
  cv2_imshow(face_all)